### ISSUE TITLE
Episode 03 (Configuration)

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/tutorial#11]
I started working on episode 03 in the current structure that is about configuration. Also, I made a draft pull request for that. 

Checklist:

- [x] make a draft version
- [x] update questions, objectives and key points
- [x] add the content
- [x] add challenges to the episode (if it is needed).

**Comment by ledm** [comment]
Hi, quick comment. Can we make sure that the tutorial user-conifig.yml turns off the auto-deletion of the preproc folder? We want people to be able to see the contents of the preproc netcdfs, settings.yml and metedata.yml files. Cheers!
