### ISSUE TITLE
renaming branch gh-pages to master

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/tutorial#17]
The initial branch "gh-pages" is changed to "master".  There are two points that need attention:

**1- lesson template** 
According to [Software Carpentry guide](https://carpentries.github.io/lesson-example/setup.html), using the gh-pages branch of the lesson template will ensure that the most “stable” version of the template repository is used. 

**2- tutorial webpage on github pages**
According to the [manual on creating gh-pages](https://opentechschool.github.io/social-coding/extras/pages.html), the site must be on the gh-pages branch. GitHub will not care about the master branch, which is the default branch in git. 

@bouweandela @ledm I am not sure whether these are already fixed.

**Comment by bouweandela** [comment]
To motivate this choice a bit: using a `master` branch as the default is the most common choice for git repositories, so it is what people expect, therefore I think that it will be easiest to work with for most people.

>1- lesson template
According to Software Carpentry guide, using the gh-pages branch of the lesson template will ensure that the most “stable” version of the template repository is used.

Could you be a bit more specific about how this relates to this `tutorial` repository and why this could be a problem?

> 2- tutorial webpage on github pages
According to the manual on creating gh-pages, the site must be on the gh-pages branch. GitHub will not care about the master branch, which is the default branch in git.

This is configurable in the repository settings, currently this is set to `master`

**Comment by SarahAlidoost** [comment]
@bouweandela thanks. Regarding lesson template, the carpentry [guideline](https://carpentries.github.io/lesson-example/setup.html) (steps 9-11) is as follows:

> To be able to pull upstream style changes, manually add the styles repository as a remote called template: git remote add template https://github.com/carpentries/styles.git
> This will allow you to pull in changes made to the template. Make sure you are using the **gh-pages** branch of the lesson template. This will ensure that you are using the most “stable” version of the template repository. 

We don't use the original carpentry template, but the modified version by escience academy. Therefore, the tutorial repository doesn't contain the remote template repo.  As ESMValGroup wants to maintain the template, the renaming branch name doesn't cause a problem anymore.

**Comment by bouweandela** [comment]
OK. Is there anything left to do on this topic?

**Comment by SarahAlidoost** [comment]
> OK. Is there anything left to do on this topic?

No, I close this issue.
