### ISSUE TITLE
Tutorial sprint 

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/tutorial#26]
@rswamina, @hb326, @bouweandela, @valeriupredoi, @nielsdrost, @zklaus, @mattiarighi, @axel-lauer, @ledm, @Peter9192

Hi all, 
We want to plan a Tutorial sprint of 3 days (virtual). The sprint covers lesson developments (adding the existing material to the repo), refactoring the episodes and reviewing the pull requests. Specifically, we will focus on the working items discussed in the shared google document.
We kindly invite you to join the sprint. To decide the date, please participate in the doodle poll the link below **by Next Monday 8th June**. Thank you.
https://doodle.com/poll/ykurzky6scdna59m

If I missed someone from the team, please mention him/her here.

**Comment by bouweandela** [comment]
This would be of interest to @ESMValGroup/userengagementteam

**Comment by valeriupredoi** [comment]
cheers @SarahAlidoost - good call! @rswamina @BenMGeo @hb326 double nudge :baseball:

**Comment by hb326** [comment]
@LisaBock: there will be a tutorial sprint of 3 days happening soon. To be precise, on the days 26 (Fri.), 29 (Mon), 30 (Tue.) June.
FYI.

**Comment by SarahAlidoost** [comment]
> @LisaBock: there will be a tutorial sprint of 3 days happening soon. To be precise, on the days 26 (Fri.), 29 (Mon), 30 (Tue.) June.
> FYI.

@LisaBock please let me know if you would like to join the sprint on those days.

**Comment by LisaBock** [comment]
> 
> 
> > @LisaBock: there will be a tutorial sprint of 3 days happening soon. To be precise, on the days 26 (Fri.), 29 (Mon), 30 (Tue.) June.
> > FYI.
> 
> @LisaBock please let me know if you would like to join the sprint on those days.

@SarahAlidoost Yes, I would like to join. But the complete three days will be difficult. I try my best...
