### ISSUE TITLE
Episode 5 (Preprocessors)

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/tutorial#30]
Working with preprocessors 

Description : More complex example- optional. This example includes a more complex preprocessor chain, perhaps turning a 3D file into a smaller regional average, but outputting a time series plot again)

Internal name : preprocessor

Tentative structure and plan :

Questions:
- How do I set up a preprocessor?
- Can I use different preprocessors for different variables?
- Can I use different datasets for different variables?

Objectives: 

- Create a recipe with multiple preprocessors
- Use different preprocessors for different variables
- Run a recipe with variables from different datasets

Contents:
- Discussion: Inspect the example recipe
- Exercise: edit the file to add a depth average preprocessor and run it
- Exercise: Make a minor edit to the recipe such as:
    - Add a new preprocessor stage, ie a depth average preprocessor, or a mask, a new regional cut.
    - Change the dataset to a different model or variable.

- Callout: How to find what CMIP data is available:
      - Link to the CMOR pages where users can find what variables exist
      - Link to ESGF page to see what data has been submitted.
 
- Key points: 
   - A recipe can run different preprocessors at the same time.
   - The setting additional_datasets can be used to add a different dataset.
   - Variable groups are useful for defining different settings for different variables. 

- Any additional things that cannot be done  or is unsupported at this time

**Comment by rswamina** [comment]
- [ ] Clone the tutorial repository

- [ ] Create a Google Doc to share the text to be added  and share link on Gitter - @rswamina

**Comment by rswamina** [comment]
- [x] Added content for introduction

- [x] Added content for questions as laid out in the Questions and Objectives section of the Google Doc.

- [x] Created examples and a Challenge

- [ ] Variable Groupings - example

- [x] Created initial Pull request

**Comment by rswamina** [comment]
@LisaBock  - Can you tell me if this recipe works for you and produces multimodel means in the preproc directory?

~~~YAML
 # recipe_variable_groups.yml
 ---
 documentation:

  description: |
   Example recipe to demonstrate grouping of variables in the diagnostic
    section. Additions made to test this recipe.

  authors:
    - schlund_manuel
    - swaminathan_ranjini

  maintainer:
   - swaminathan_ranjini

  projects:
   - crescendo
preprocessors:
  statistics:
    multi_model_statistics:
      span: full
      statistics: [mean, median]

  mask:
    mask_landsea:
      mask_out: sea


cmip5_datasets: &cmip5_datasets
  - {dataset: CanESM2, ensemble: "r(1:4)i1p1", project: CMIP5}
  - {dataset: MPI-ESM-LR, ensemble: "r(1:2)i1p1", project: CMIP5}


cmip6_datasets: &cmip6_datasets
  - {dataset: UKESM1-0-LL, ensemble: "r(1:4)i1p1f2", grid: gn, project: CMIP6}
  - {dataset: CanESM5, ensemble: "r(1:4)i1p2f1", grid: gn, project: CMIP6}

diagnostics:

  diag_variable_groups:
    description: Demonstrate the use of variable groups.
    variables:
      tas_cmip5: &variable_settings # need a name for the grouping
        short_name: tas # specify variable to look for
        mip: Amon
        exp: historical
        start_year: 2000
        end_year: 2005
        tag: TAS_CMIP5 #tag is optional if you are using these settings just once
        additional_datasets: *cmip5_datasets
      tas_obs:
        <<: *variable_settings
        preprocessor: mask
        tag: TAS_OBS
        additional_datasets:
          - {dataset: HadCRUT4, project: OBS, type: ground, version: 1, tier: 2}
      tas_cmip6:
        <<: *variable_settings
        tag: TAS_CMIP6 #nothing changes except the data set
        additional_datasets: *cmip6_datasets
    scripts: null
~~~

**Comment by LisaBock** [comment]
I think you missed to call the preprocessor "statistics".

**Comment by LisaBock** [comment]
> 
> 
> @LisaBock - Can you tell me if this recipe works for you and produces multimodel means in the preproc directory?
> 
> ```yaml
>  # recipe_variable_groups.yml
>  ---
>  documentation:
> 
>   description: |
>    Example recipe to demonstrate grouping of variables in the diagnostic
>     section. Additions made to test this recipe.
> 
>   authors:
>     - schlund_manuel
>     - swaminathan_ranjini
> 
>   maintainer:
>    - swaminathan_ranjini
> 
>   projects:
>    - crescendo
> preprocessors:
>   statistics:
>     multi_model_statistics:
>       span: full
>       statistics: [mean, median]
> 
>   mask:
>     mask_landsea:
>       mask_out: sea
> 
> 
> cmip5_datasets: &cmip5_datasets
>   - {dataset: CanESM2, ensemble: "r(1:4)i1p1", project: CMIP5}
>   - {dataset: MPI-ESM-LR, ensemble: "r(1:2)i1p1", project: CMIP5}
> 
> 
> cmip6_datasets: &cmip6_datasets
>   - {dataset: UKESM1-0-LL, ensemble: "r(1:4)i1p1f2", grid: gn, project: CMIP6}
>   - {dataset: CanESM5, ensemble: "r(1:4)i1p2f1", grid: gn, project: CMIP6}
> 
> diagnostics:
> 
>   diag_variable_groups:
>     description: Demonstrate the use of variable groups.
>     variables:
>       tas_cmip5: &variable_settings # need a name for the grouping
>         short_name: tas # specify variable to look for
>         mip: Amon
>         exp: historical
>         start_year: 2000
>         end_year: 2005
>         tag: TAS_CMIP5 #tag is optional if you are using these settings just once
>         additional_datasets: *cmip5_datasets
>       tas_obs:
>         <<: *variable_settings
>         preprocessor: mask
>         tag: TAS_OBS
>         additional_datasets:
>           - {dataset: HadCRUT4, project: OBS, type: ground, version: 1, tier: 2}
>       tas_cmip6:
>         <<: *variable_settings
>         tag: TAS_CMIP6 #nothing changes except the data set
>         additional_datasets: *cmip6_datasets
>     scripts: null
> ```

@rswamina I think you missed to call the preprocessor "statistics".

**Comment by rswamina** [comment]
Yes. it was pointed out to me...will fix and rerun. Thanks!
