### ISSUE TITLE
Episode 0: Title Page

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/tutorial#37]
**Short description of the material**
This is the title page.
 
**Branch and pull request**
We'll be working in a google doc first. Please contact @ledm if you want access to the google doc.

The PR is in #38.

Title page:
- prereq:
  - Basic understanding of Git 
  - Basic understanding of your preferred command line interface (ie a bash terminal)
  - Github account
  - Access to CMIP data
  - Access to a suitable computing system (egie jasmin)
- Main things you need to know before starting this course:
  - This tutorial can be taken online independently or taught by one of our instructors.
-  Please check the common issues page if you get stuck. Otherwise, help is always available from ESMValTool developers via the github issues page.  
  - This tutorial includes several advanced lessons after the conclusion. These advanced lessons should be treated like “mini-tutorials”, and include aspects like “developing your own diagnostic” or “how to include observations”.
- What will you learn in this course:
  - What is ESMValTool
  - How to install ESMValTool
  - How to run ESMValTool
  - How to develop your own diagnostics and recipes
  - How to contribute your recipes and diagnostics back into ESMValTool

**Comment by JaroCamphuijsen** [comment]
I believe that by merging #38, this issue is also closed.
